### ISSUE TITLE
Translate `slowmodesec` to zh-hant-tw

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/Send2KindleBot#108]
https://github.com/GabrielRF/Send2KindleBot/blob/9c0b8514afbadc57a5884f13476f7a788f0165fc/i18n/bot.zh-hant-tw.yml#L8

**Comment by Reghill** [comment]
Could you please assign this to me? I would like to work on this.

**Comment by GabrielRF** [comment]
#140
