### ISSUE TITLE
Translate bot to Indonesian

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/Send2KindleBot#13]
Translate `bot.en-us.yml` to Indonesian
https://github.com/GabrielRF/Send2KindleBot/blob/master/i18n/bot.en-us.yml

**Comment by TheFaR8** [comment]
Can I work on this please?

**Comment by GabrielRF** [comment]
@TheFaR8 Sure! I would be glad with your help!

**Comment by GabrielRF** [comment]
Thanks for your work! It's already working!

**Comment by TheFaR8** [comment]
You're welcome :))
