### ISSUE TITLE
Translate bot to French

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/Send2KindleBot#15]
Translate `bot.en-us.yml` to French
https://github.com/GabrielRF/Send2KindleBot/blob/master/i18n/bot.en-us.yml

**Comment by kedMertens** [comment]
I have started to work on it!

**Comment by GabrielRF** [comment]
@exitttttt @kedMertens @fastest10
Is it ready? Should I consider #33 or #36?

**Comment by kedMertens** [comment]
> @exitttttt @kedMertens @fastest10
> Is it ready? Should I consider #33 or #36?

@GabrielRF , will look through in couple hours. 
Not sure which one should be taken into consideration. Will give you my opinion on that.

**Comment by kedMertens** [comment]
@GabrielRF, should it be considered #33 and #36 as spam?

**Comment by tducasse** [comment]
> 
> 
> @tducasse are you going to create new PR or you are up to review existed ones?

I am going to create a new PR

**Comment by tducasse** [comment]
Done!

**Comment by exitttttt** [comment]
> Hi,
> I'm french, and I just had a look at the two pull requests #33 and #36, and it's either google translate or someone that does not speak french as a native speaker. There are various grammatical mistakes.
> 
> I'm going to create a third pull request soon.

I'm ok for the grammatical mistake and maybe with some phrasing that are not the best, but saying it's from Google translate or not a native speaker...

But I guess it's French so we could just argue 30 minutes on the word "Courriel" VS "E-mail".

**Comment by tducasse** [comment]
I'm sorry, but you wrote things like "envoyer moi", "ce robot envoient", "que fais le robot", "attendez puis vérifier" (etc), and this is the kind of mistake Google translate makes

**Comment by exitttttt** [comment]
I do agree that your translation could be more correct, but I don't really understand why the term robot is wrong here (maybe that was not the word that you was pointing out but more the "sentence").

I'm not trying to argue, I'm just trying to get a better understanding for my next translation.

**Comment by tducasse** [comment]
"Ce robot" is singular, and "envoient" is the plural form of the verb "envoyer". It should be "ce robot envoie".
As for the rest, it should be "envoyez moi", "attendez puis vérifiez", "que fait ce robot". Just some small conjugation mistakes.

**Comment by GabrielRF** [comment]
Thanks for all the work, guys! I'm very happy the way things went. I've never expected so many people would offer their time to improve the bot! 

Now there are four PRs translating the bot to French.
#33, #36, #41 and #44. 

Any suggestions on which should be merged?

**Comment by tducasse** [comment]
I just reviewed all of them very quickly. 
#33 sounds wrong, it seems like Google translate to me.
#36 is not that bad, but a lot of conjugation mistakes here and there.
#41 is mine, so I can't really talk about it, but I can guarantee the French is correct.
#44 is not bad, but small mistakes here and there, grammar and spelling.

**Comment by kedMertens** [comment]
I found that #41 is best choice for merge. It is done by native speaker @tducasse and without grammar mistakes.

**Comment by GabrielRF** [comment]
@tducasse Made a small review on your PR. As soon as it is fixed, I'll merge it.

**Comment by GabrielRF** [comment]
@tducasse About what I said on the review.. 
Try, for example, sending a message to [@userinfobot](https://t.me/userinfobot)
If I set the language of my app to French, then the bot tells me my language is `fr`
What does the bot answers to you as your language?

**Comment by GabrielRF** [comment]
Issue closed! Thanks for all the help!

**Comment by GabrielRF** [comment]
@tducasse @kedMertens 
Can you take a look at #66, please?

**Comment by tducasse** [comment]
Done
