### ISSUE TITLE
Can't find setting to change 'Sender Email'

### ISSUE THREAD

**Issue by malaguer** [GabrielRF/Send2KindleBot#157]
First of all, congrats for such an excellent bot. It is very useful and practical.

Maybe it is a stupid question and I'm missing the option to do it, but after consulting your Help and Info commands I can't find a way to change Sender Email. I've only seen how to change Kindle Mail. Am I missing something?

Thanks in advance.

**Comment by GabrielRF** [comment]
@malaguer The button to change the e-mail will detect automatically which e-mail should be changed. 
Please, check if it works for you and let me know if there is any translation problem with the text.

**Comment by malaguer** [comment]
You're right! Tested and it has worked like a charm. I thought the option was only for Kindle Email address.

Thank you for clarifying and, again, congrats for your works!

**Comment by GabrielRF** [comment]
@malaguer That's great! Sorry it took me a while to see the issue. 
I'm glad it worked. :smile:
