### ISSUE TITLE
Max Upload size

### ISSUE THREAD

**Issue by iTheProMan** [GabrielRF/Send2KindleBot#159]
Kindle now supports files up to 200 MB can you please ad this feature to the bot also?

**Comment by GabrielRF** [comment]
@iTheProMan I don't think it is possible. 
Even though I can make the bot download bigger files, usually an email can't be bigger than 25MB. 
So it is not a bot limitation, but an email limitation.

**Comment by GabrielRF** [comment]
@iTheProMan The bot will send an email anyway. So the email would limit the file size.
