### ISSUE TITLE
Unregister email 

### ISSUE THREAD

**Issue by effemmeffe** [GabrielRF/Send2KindleBot#160]
I'm using the bot (great work, BTW!) and I keep getting mails from amazon asking to confirm the document.
I set my kindle email with the button, but if I check with the command /start I see two emails registered.
How can I unregister one of them?

**Comment by GabrielRF** [comment]
@effemmeffe The bot needs two e-mails to work. It won't work having only one of them. If you need further information, call me on Telegram. GabrielRF.

**Comment by effemmeffe** [comment]
Hi, I don't know how to contact you on telegram, so I'll write here: I set two emails, and if I check emails in the bot they are correct.
