### ISSUE TITLE
EPUB  not arriving on my kindle.

### ISSUE THREAD

**Issue by beriadan77** [GabrielRF/Send2KindleBot#161]

**Comment by beriadan77** [comment]
Hi! So, I've set the two emails correctly. I understand that your bot sends the ebook directly from the provided email so I should not need to add any specific bot-email to my Amazon account allowed emails configuration, correct?
Still It's been over 10 min and I'm still not seeing the book. I tried sending it myself over email from my phone and it worked fine.
Any ideas? Thank you so much!

**Comment by GabrielRF** [comment]
@beriadan77 Have you checked your mailbox? Amazon must have sent you a message.
