### ISSUE TITLE
Translate bot to Italiano

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/Send2KindleBot#17]
Translate `bot.en-us.yml` to Italiano
https://github.com/GabrielRF/Send2KindleBot/blob/master/i18n/bot.en-us.yml

**Comment by teopost** [comment]
ok. I'll do it

**Comment by GabrielRF** [comment]
@teopost Grazie

**Comment by cipi1965** [comment]
I created a PR (#24)

**Comment by GabrielRF** [comment]
@cipi1965 @alsoknownasdrew @teopost 
Thanks for your PRs! Can you help me to choose between #24 and #35?

**Comment by GabrielRF** [comment]
@alsoknownasdrew Ok, then
Thank you all for the effort!
