### ISSUE TITLE
Translate bot to Español

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/Send2KindleBot#18]
Translate `bot.en-us.yml` to Español
https://github.com/GabrielRF/Send2KindleBot/blob/master/i18n/bot.en-us.yml

**Comment by yonijuerga** [comment]
starting translation

**Comment by NefixEstrada** [comment]
I'm doing this one

**Comment by NefixEstrada** [comment]
Oh, you were faster :(

**Comment by kedMertens** [comment]
> 
> 
> Oh, you were faster :(

You can help @yonijuerga by reviewing his PR. It will improve translation!

**Comment by yonijuerga** [comment]
no hay problema @NefixEstrada, me estoy encontrando problemas con esto .), haz la traduccion tu si quieres. saludos!

**Comment by NefixEstrada** [comment]
Okay

**Comment by falbala84** [comment]
He añadido algunas correcciones, espero que nadie se moleste.

**Comment by GabrielRF** [comment]
I've just received a new PR 
#42 
What do you think about it?
