### ISSUE TITLE
Translate bot to Nederlands

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/Send2KindleBot#19]
Translate `bot.en-us.yml` to Nederlands
https://github.com/GabrielRF/Send2KindleBot/blob/master/i18n/bot.en-us.yml

**Comment by GabrielRF** [comment]
@TomG777 @rvben Can you help me decide between #29 and #39?

**Comment by rvben** [comment]
Ah, I didn't notice that there was another PR for the dutch translation. My bad. I'll take a look.

**Comment by rvben** [comment]
We might be able to come up with a better translation together :)
There are a couple of things that I would and did translate differently, f.e.
- Kindle-indeling; 'indeling' is not a word that I think fits here.

So, please accept his PR, and I'll do a PR for some refinements. That's the least I can do.

**Comment by GabrielRF** [comment]
@rvben Done. Accepted #39 

Thank you all for the work! I'm really fascinated the way everybody is helping the bot!
