### ISSUE TITLE
Add Portuguese (and more) as an option

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/Send2KindleBot#2]
https://core.telegram.org/bots/api#user
`language_code | String | Optional. IETF language tag of the user's language`

**Comment by kedMertens** [comment]
Hi, @GabrielRF !
I would like to contribute in your project.
In frame of the issue, I could add French and Russian as options.
What do you think?

**Comment by GabrielRF** [comment]
Hi, @kedMertens 
It would be nice!!

I'm not familiar with the best way to prepare the file to be translated. Are you experienced with it?

**Comment by kedMertens** [comment]
> Hi, @kedMertens
> It would be nice!!
> 
> I'm not familiar with the best way to prepare the file to be translated. Are you experienced with it?

No, I will investigate the question and propose options, which we could discuss.

**Comment by rougeth** [comment]
[This](https://www.mattlayman.com/blog/2015/i18n/) is a great guide on how to handle i18n in Python. It basically covers this part of Python docs (https://docs.python.org/3/library/i18n.html).

**Comment by kedMertens** [comment]
> [This](https://www.mattlayman.com/blog/2015/i18n/) is a great guide on how to handle i18n in Python. It basically covers this part of Python docs (https://docs.python.org/3/library/i18n.html).

Thanks for the links. I'll start to work from here.

**Comment by kedMertens** [comment]
@GabrielRF, @rougeth, here is what I found out. 
In order to provide multi-language feature following steps has to be applied :
1. Wrap desired strings from pdftokindlebot.py with `_()` , that mark will highlight text for next step. 
2. Generate Portable Object Template (POT) file, the file will contain all marked strings. To generate one, several tools are available: xgettext, xpot, standard python script pygettext.py and Babel library. 
3. Add translations of the text to POT file and generate Portable Object (PO), Machine Object (MO) files. Filling POT file can be done manually or with help of third party services, for instance [Transifex ](https://www.transifex.com/) - provides translation and generates PO, MO files, open-source translations editor is [Poedit ](https://poedit.net/), Babel library methods.
4. Add [gettext ](https://docs.python.org/3/library/gettext.html) module to pdftokindlebot.py.
5. Modify source-code to enable translation options based on user language_code or with bot commands to change language on fly.

I can open a PR and start to work with respect to revealed algorithm.
Will be glade to hear your feedback.

**Comment by rougeth** [comment]
I cannot think any other step to add, great work! I believe that a lot of lines will be changed, so probably breaking this issue into some PRs will make it easier to review. Thanks @kedMertens 👍

**Comment by GabrielRF** [comment]
https://github.com/GabrielRF/Send2KindleBot/tree/i18n

I've studied a little and found a library to help translating the messages.
Here is a first attempt (not yet completed in pt_br) https://github.com/GabrielRF/Send2KindleBot/commit/36d737fb5e036c22221b41ceaee10cee4bd8f4b8

**Comment by kedMertens** [comment]
> 
> 
> I've studied a little and found a library to help translating the messages.
> Here is a first attempt https://github.com/GabrielRF/Send2KindleBot/tree/i18n
> 
> I'm not familiar with i18n.. But I liked this method because it's very simple.
> What do you @rougeth and @kedMertens think?

@GabrielRF , liked it! Looks pretty much as implementation of gettext module. 
After merging the PR we can start to expand i18n folder with different languages.
Should we provide possibility to manually switch between languages?
I would love to work on both.

**Comment by GabrielRF** [comment]
@kedMertens 
`Should we provide possibility to manually switch between languages?`
In my opinion, no. 
- I believe it is better to the user if the bot changes automatically. I want to make it easy to the user. I like to have the least buttons/commands as possible
- Doing it automatically, as it is now, I don't have to change the database. hehe

 `After merging the PR we can start to expand i18n folder with different languages.`
Perfect! I did the changes as a test. After all, I would like to get opinions before merging it. 
Also I liked the method because it works automatically when a new language is added. There is no need to change the code.

**Comment by GabrielRF** [comment]
To make the repo organized, i'm closing this issue and opened one for each language.

**Comment by kedMertens** [comment]
@GabrielRF, I would like to propose to add to all issues that you have created recently hacktoberfest tag.
It is open source celebrating event, which is going on right now on github, here is a [link](https://hacktoberfest.digitalocean.com/). I believe that it is great opportunity to get attention from native speakers to contribute to translation issues) With that tag repository of the project will appear in official web-page. Here is some tips from it 
![image](https://user-images.githubusercontent.com/39831696/46288196-a428d480-c58d-11e8-8b3e-fa51397b0678.png)

**Comment by GabrielRF** [comment]
@kedMertens I was adding labels as you answered here. hehe

`Maybe I could make some documented steps in order to provide guidance to new contributors on how to wrap translation?`
Can you do that? It would be awesome!

**Comment by kedMertens** [comment]
> 
> 
> @kedMertens I was adding labels as you answered here. hehe
> 
> `Maybe I could make some documented steps in order to provide guidance to new contributors on how to wrap translation?`
> Can you do that? It would be awesome!

@GabrielRF will try my best. 
We can create a [CONTRIBUTING.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426) and provide guidelines for the translation issues there.
