### ISSUE TITLE
Translate bot to Deutsch

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/Send2KindleBot#20]
Translate `bot.en-us.yml` to Deutsch
https://github.com/GabrielRF/Send2KindleBot/blob/master/i18n/bot.en-us.yml

**Comment by GabrielRF** [comment]
@midnightrun Fixed. Thank you!

Your help would be more than welcome!

**Comment by midnightrun** [comment]
#31 done.

**Comment by GabrielRF** [comment]
@midnightrun Thank you very much!
