### ISSUE TITLE
Translate bot to Brazilian Portuguese

### ISSUE THREAD

**Issue by silvinho485** [GabrielRF/Send2KindleBot#22]

**Comment by GabrielRF** [comment]
@silvinho485 Está feita e funcionando já. 
Não está funcionando para você?

**Comment by rerodrigues** [comment]
@silvinho485 @GabrielRF Ia me candidatar, mas parece não ser necessário. Se precisarem de ajuda em algo dêem um toque.

**Comment by GabrielRF** [comment]
@rerodrigues Português eu mesmo fiz 
Por enquanto está sem acentos porque tive um probleminha com o utf-8
Pretendo corrigir em breve
Foi problema do servidor mesmo, não do código... 
Mas obrigado por se oferecer!

**Comment by rerodrigues** [comment]
@GabrielRF Boa! Sucesso! 👍

**Comment by GabrielRF** [comment]
Resolvido. Corrigidos os acentos.
Muito obrigado a todos!
