### ISSUE TITLE
Translate bot to Russian

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/Send2KindleBot#6]
Translate `bot.en-us.yml` to Russian
https://github.com/GabrielRF/Send2KindleBot/blob/master/i18n/bot.en-us.yml

**Comment by kedMertens** [comment]
@GabrielRF, I'm on it!

**Comment by GabrielRF** [comment]
Great!

**Comment by uburuntu** [comment]
Me too :stars:

**Comment by gim-** [comment]
It would be better to use some collaborative translation app, otherwise it seems like @kedMertens and @uburuntu are working on 2 independent translations now

**Comment by nirakon** [comment]
I can help, add me in Telegram @ivantoriya

**Comment by nirakon** [comment]
> 
> 
> It would be better to use some collaborative translation app, otherwise it seems like @kedMertens and @uburuntu are working on 2 independent translations now

Let's make a group chat in Telegram?

**Comment by GabrielRF** [comment]
@gim- I'm not familiar with that. Do you have an app suggestion?

**Comment by DelevoXDG** [comment]
I can help with it too. My telegram is @delevo

**Comment by voidfault** [comment]
Wassup y'all?
How many translators, I'm not sure you need me (но я с вами) :smile:
> Do you have an app suggestion?

Yes! What about https://phraseapp.com? GitHub integration and other good enough tips

**Comment by kedMertens** [comment]
Hey everybody! I have created a PR, so we can collaborate to provide clear translation!
I could create a Telegram group for the purpose, as it was proposed by @nirakon.

**Comment by Joes-Madness** [comment]
Hi
https://github.com/Joes-Madness/Send2KindleBot/blob/patch-1/i18n/bot.ru-ru.yml

**Comment by voidfault** [comment]
I'm fool. PhraseApp needs too much for such a small task (desktop client for example).
And we're all working with telegram bot, it would be a crime not to use it.

**Comment by GabrielRF** [comment]
Done on PR #52
