### ISSUE TITLE
Bot status?

### ISSUE THREAD

**Issue by rayshan** [GabrielRF/Send2KindleBot#71]
Thanks for building this!

Is it possible to host a service status page? Maybe use something free like https://betteruptime.com.

I just sent a file and a link. They weren't sent to my Kindle and I didn't get a "File sent" response.

Also clicking on the Telegram link is showing:

<img width="513" alt="Screen Shot 2020-11-05 at 10 26 31 AM" src="https://user-images.githubusercontent.com/3760840/98281991-6491fb00-1f52-11eb-815e-7161da3b2ce1.png">

**Comment by GabrielRF** [comment]
Sorry, I did not understand it.
The correct link is https://t.me/Send2KindleBot
Is looks like you missed the `bot` word

**Comment by rayshan** [comment]
You're right, the telegram link works. I still didn't get the file and the link I sent yesterday though.

**Comment by GabrielRF** [comment]
Talk to me on Telegram and I'll try to help you :)
