### ISSUE TITLE
Translate bot to Malayalam

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/Send2KindleBot#9]
Translate `bot.en-us.yml` to Malayalam
https://github.com/GabrielRF/Send2KindleBot/blob/master/i18n/bot.en-us.yml

**Comment by Waterloo** [comment]
I am interested in contributing.

**Comment by GabrielRF** [comment]
@Waterloo Thank you very much! I'm glad you are taking your time to do it.

**Comment by GabrielRF** [comment]
@Waterloo Thank you very much
